### ISSUE TITLE
BROKEN BUILD

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [zowens/crc32c#70]
Hi,

My project has crc32c as sub-dependency to that crates.
I'm facing to a build issue (into docker with a base of ubuntu bookworm).

The error is:
```
#11 64.47 error: unsupported output in build script of `crc32c v0.6.7`: `cargo::rustc-check-cfg=cfg(armsimd)`
#11 64.47 Found a `cargo::key=value` build directive which is reserved for future use.
#11 64.47 Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
#11 64.47 See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
```

I think these [lines](https://github.com/zowens/crc32c/blob/master/build.rs#L196) seems incorrect.

It it possible to look on it to fix it/revert merge from yesterday ?

**Comment by IgorLaborieWefox** [comment]
I have the same issue with Rust v1.76.0.
Switching to Rust v1.78.0 fixes that issue.

**Comment by MarcAntoine-Arnaud** [comment]
Cool it fix for me too, thank for the tips.

**Comment by jbg** [comment]
What's the MSRV of this crate?

**Comment by zowens** [comment]
This should be fixed in 0.6.8 (#71 ) which includes the fix from #69.

**Comment by nickalcock** [comment]
Still broken. There's still
```
         println!("cargo::rustc-cfg=armsimd");
```
in there, which is still a key::value output and is still banned on non-nightly :)
